### ISSUE TITLE
Performance issues with the timeline feature

### ISSUE THREAD

**Issue by worldtiki** [ExpediaDotCom/haystack#611]
Hi folks!

We've been having issues with the timeline feature in our development environment and I'd love to have some feedback or suggestions on how we can improve this.

Our current set up is:
**Elasticsearch**
- running as a managed service on AWS
- using version 5.6
- m4.large.elasticsearch
- 6 nodes (3 masters)

**Trace Reader**
- running in a Kubernetes cluster
- version 1.0.4
- worker nodes are m4.large.elasticsearch but we're asking kube for 0.25 cpu and 0.5G jvm heap (cpu usage is very very low)
- 2 instances/replicas
- configured to create the ES templates with number_of_replicas: 1 and number_of_shards: 3

**Trace Indexer**
- running in a Kubernetes cluster
- version 1.0.4
- worker nodes are m4.large.elasticsearch but we're asking kube for 1 cpu and 4G jvm heap (cpu usage is very very low)
- 2 instances/replicas

**Indices**
`green open haystack-traces-2018-11-15-2 qg2MsZekTQGPl6Vg-EYN5A 3 1 732468 0 39.5mb 20.7mb
green open haystack-traces-2018-11-15-1 Xgrr10B2ReqAlMC5Z8HeDA 3 1 844645 0 40.9mb 20.4mb`
totalling around 1.5 million documents

The ttl (used in the curator-es-index-store) is of 1 day but we manually deleted some of the old indices that's why only 2 show up above.

**The problem**
Queries to the timeline either return very quick:
`2018-11-15 13:59:27:265 grpc-default-worker-ELG-4-8, INFO, c.e.www.haystack.trace.reader.stores.readers.es.ElasticSearchReader,  "elastic count query requested: Search{uri=haystack-traces-2018-11-15-2/spans/_search, method=POST}', query: '{  "size" : 0,  "query" : {    "bool" : {      "filter" : [        {          "nested" : {            "query" : {              "bool" : {                "filter" : [                  {                    "term" : {                      "spans.servicename" : {                        "value" : "pda",                        "boost" : 1.0                      }                    }                  }                ],                "adjust_pure_negative" : true,                "boost" : 1.0              }            },            "path" : "spans",            "ignore_unmapped" : false,            "score_mode" : "none",            "boost" : 1.0          }        }      ],      "adjust_pure_negative" : true,      "boost" : 1.0    }  },  "aggregations" : {    "countagg" : {      "histogram" : {        "field" : "starttime",        "interval" : 3.0E8,        "offset" : 0.0,        "order" : {          "_key" : "asc"        },        "keyed" : false,        "min_doc_count" : 0,        "extended_bounds" : {          "min" : 1.5422865E15,          "max" : 1.542290399999999E15        }      }    }  }}'" 
2018-11-15 13:59:27:308 scala-execution-context-global-122, INFO, com.expedia.www.haystack.trace.reader.services.GrpcHandler,  "service invocation for operation=TraceReader/getTraceCallGraph and request=startTime: 1542286500000000
endTime: 1542290399999999
interval: 300000000
filterExpression {
  operands {
    field {
      name: "serviceName"
      value: "pda"
    }
  }
}
 completed successfully"`

Or hang and eventually timeout:
`2018-11-15 13:59:36:013 grpc-default-worker-ELG-4-7, INFO, c.e.www.haystack.trace.reader.stores.readers.es.ElasticSearchReader,  "elastic count query requested: Search{uri=haystack-traces-2018-11-15-2/spans/_search, method=POST}', query: '{  "size" : 0,  "query" : {    "bool" : {      "filter" : [        {          "nested" : {            "query" : {              "bool" : {                "filter" : [                  {                    "term" : {                      "spans.servicename" : {                        "value" : "pda",                        "boost" : 1.0                      }                    }                  }                ],                "adjust_pure_negative" : true,                "boost" : 1.0              }            },            "path" : "spans",            "ignore_unmapped" : false,            "score_mode" : "none",            "boost" : 1.0          }        }      ],      "adjust_pure_negative" : true,      "boost" : 1.0    }  },  "aggregations" : {    "countagg" : {      "histogram" : {        "field" : "starttime",        "interval" : 3.0E8,        "offset" : 0.0,        "order" : {          "_key" : "asc"        },        "keyed" : false,        "min_doc_count" : 0,        "extended_bounds" : {          "min" : 1.5422865E15,          "max" : 1.542290399999999E15        }      }    }  }}'" 
2018-11-15 13:59:49:341 pool-2-thread-1, ERROR, c.e.w.haystack.trace.commons.config.reload.ConfigurationReloadProvider,  "Fail to reload the configuration from elastic search for observer name=indexing-fields. Will try at next scheduled time" java.net.SocketTimeoutException: Read timed out\n	at java.net.SocketInputStream.socketRead0(Native Method)\n	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)\n	at java.net.SocketInputStream.read(SocketInputStream.java:171)\n	at java.net.SocketInputStream.read(SocketInputStream.java:141)\n	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)\n	at sun.security.ssl.InputRecord.read(InputRecord.java:503)\n	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)\n	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)\n	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)\n	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)\n	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)\n	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)\n	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)\n	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)\n	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)\n	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)\n	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)\n	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)\n	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)\n	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)\n	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)\n	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)\n	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)\n	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)\n	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)\n	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:132)\n	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:67)\n	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:60)\n	at com.expedia.www.haystack.trace.commons.config.reload.ConfigurationReloadElasticSearchProvider.$anonfun$load$2(ConfigurationReloadElasticSearchProvider.scala:56)\n	at scala.util.Try$.apply(Try.scala:209)\n	at com.expedia.www.haystack.commons.retries.RetryOperation$.executeWithRetryBackoff(RetryOperation.scala:59)\n	at com.expedia.www.haystack.commons.retries.RetryOperation$.executeWithRetryBackoff(RetryOperation.scala:53)\n	at com.expedia.www.haystack.trace.commons.config.reload.ConfigurationReloadElasticSearchProvider.$anonfun$load$1(ConfigurationReloadElasticSearchProvider.scala:56)\n	at com.expedia.www.haystack.trace.commons.config.reload.ConfigurationReloadElasticSearchProvider.$anonfun$load$1$adapted(ConfigurationReloadElasticSearchProvider.scala:49)\n	at scala.collection.immutable.List.foreach(List.scala:389)\n	at com.expedia.www.haystack.trace.commons.config.reload.ConfigurationReloadElasticSearchProvider.load(ConfigurationReloadElasticSearchProvider.scala:49)\n	at com.expedia.www.haystack.trace.commons.config.reload.ConfigurationReloadProvider.$anonfun$new$1(ConfigurationReloadProvider.scala:34)\n	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)\n	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)\n	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)\n	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n	at java.lang.Thread.run(Thread.java:748)\n`

**Metrics**

![image](https://user-images.githubusercontent.com/1187103/48557763-831f0780-e8df-11e8-9e9c-fcc549a316dc.png)

![image](https://user-images.githubusercontent.com/1187103/48557803-9e8a1280-e8df-11e8-8e19-b5b0b2c99e02.png)

![image](https://user-images.githubusercontent.com/1187103/48558054-3556cf00-e8e0-11e8-8e0d-13cfb753223c.png)

![image](https://user-images.githubusercontent.com/1187103/48557834-b5c90000-e8df-11e8-9ba1-198c56ce1fcb.png)

![image](https://user-images.githubusercontent.com/1187103/48558124-6505d700-e8e0-11e8-8729-65dbee37c50f.png)

**Comment by ashishagg** [comment]
Thanks for reporting this and working offline to reproduce this issue.
We have got a fix in this PR.
https://github.com/ExpediaDotCom/haystack-traces/pull/204

You can try the docker image with version 'c2ae83195dca0b073b9ea164cbfee158536fe54c' and let us know. We will close this issue once you verify.

**Comment by worldtiki** [comment]
Thanks. I no longer have any performance issues.
I also enabled a filter on our Pitchfork collector to drop spans with invalid timestamps. I'm removing it now and will recheck the performance again without this filter.

**Comment by worldtiki** [comment]
Confirmed that even with no filters the feature works fine. You can close the ticket :)

**Comment by ashishagg** [comment]
Thanks!. Closing this issue.
